// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMfchedDV4dYoracbACjFmggpAE1Q4PiQ',
    appId: '1:824378149313:web:57004204ed3d0815500740',
    messagingSenderId: '824378149313',
    projectId: 'flashcard-final',
    authDomain: 'flashcard-final.firebaseapp.com',
    storageBucket: 'flashcard-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPuiHmpGaLGB1WpMGE1NzaUfM2_5H2gkg',
    appId: '1:824378149313:android:aa50f94c086d0e10500740',
    messagingSenderId: '824378149313',
    projectId: 'flashcard-final',
    storageBucket: 'flashcard-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz9Oc3RiVnffSXcJopk2j3iX1yzhgbvYU',
    appId: '1:824378149313:ios:5c60ab732f21110a500740',
    messagingSenderId: '824378149313',
    projectId: 'flashcard-final',
    storageBucket: 'flashcard-final.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz9Oc3RiVnffSXcJopk2j3iX1yzhgbvYU',
    appId: '1:824378149313:ios:5c60ab732f21110a500740',
    messagingSenderId: '824378149313',
    projectId: 'flashcard-final',
    storageBucket: 'flashcard-final.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
